spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/btt_pay
    username: <Insert username here>
    password: <Insert password here>
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

# Logging Properties
logging:
  level:
    ROOT: INFO
    com.btt.pay: DEBUG

# JWT Properties
jwt:
  secret: QmlnIFRyYWRpbmcgVHJhZGVycyBQYXkgU2VydmljZSBTZWNyZXQgS2V5
  expiration: 86400000